[package]
name = "rust-vim"
version = "0.1.0"
edition = "2024"

[dependencies]
count-digits = "0.5.1"
crossterm = "0.29.0"
io = "0.0.2"
ratatui = "0.29.0"
regex = "1.12.2"
ropey = "1.6.1"
structopt = "0.3.26"
unicode-display-width = "0.3.0"
